/**
 * PLEASE NOTE: This file was initially generated by Claude 4 Sonnet
 * based upon my design document. I am using JetBrains AI for WebStorm
 *
 * I am experimenting with having AI write my unit tests.
 *
 * Why am I telling you this? FULL DISCLOSURE!!!
 *
 * So what was the result?
 * 	1. It picked up an Enum from the Hold That Tower game - obviously my prompt was not specific enough.
 * 	2. It created a MockSnake and MockPitch - good. (edit: Actually, I need to bring in the actual classes)
 * 	3. It set the defaults in PrizeType incorrectly - I blame my prompt on that again
 * 	4. Too many tests on the collision() method - you only need one failure
 * 	5. 'No Collision' test was poorly done. The expect was within an 'if' statement. Yipes!!
 * 	6. Tested for both the position and the (x,y) or position. Overkill.
 * 	7. Had a series of 3 tests to test for an invalid PrizeType. Really??????
 * 	8. Had an entire of 3 tests to test for invalid values. Sorry, Charlie.
 * 	9. Tested for valid position generation. This is a private method, so no testing required. I fault my prompt on that one.
 * 	10. Tested for valid UUID generation. Ok, that's just plain weird.
 *
 * 	All in all, I say I kept maybe 60% of the code? Maybe 65%?
 *
 * 	I need to make sure that it doesn't generate tests for private methods.
 *
 * 	But I'm pleased. It saved me about 15 minutes time. I mean, this is a small class.
 * 	I imagine on much larger classes it may save more time.
 */
import { MockVector } from "../../tdd-utilities/tddUtilities.js";
import Snake from "../Snake/Snake.js";
import Pitch from "../Pitch/Pitch.js";
import Prize from "./Prize.js";
import PrizeType from "./PrizeType.js";
import Vector from "../Vector/Base/Vector.js";

describe('And when I work with the Prize class', () => {
	const id = 'test-prize';
	const type = PrizeType.APPLE;
	const value = 10;
	const pitch = new Pitch({ dimensions: new MockVector(10, 10) });
	const snake = new Snake({ position: new MockVector(5,5), direction: MockVector.Up() });
	let prize;

	it('should throw an error if pitch is not provided', () => {
		expect(() => new Prize({ type, value, snake, pitch: 'bad' }))
			.to.throw(`'pitch' argument must be an instance of Pitch`);
	});

	it('should throw an error if snake is not provided', () => {
		expect(() => new Prize({ type, value, pitch, snake: 'bad' }))
			.to.throw(`'snake' argument must be an instance of Snake`);
	});

	it('should throw error if type is invalid', () => {
		expect(() => new Prize({ type: 'bad', value, pitch, snake }))
			.to.throw(`'type' argument must be a valid PrizeType`);
	});

	it('should create a prize with default properties', () => {
		prize = new Prize({ pitch, snake });
		expect(prize).to.be.instanceOf(Prize);
		expect(prize.id).to.be.a('string');
		expect(prize.type).to.equal(PrizeType.DEFAULT_TYPE);
		expect(prize.value).to.equal(PrizeType.DEFAULT_VALUE);
		expect(prize.position).to.be.instanceOf(Vector);
	});

	describe('And I work with the Public properties', () => {
		beforeEach(() => {
			prize = new Prize({ id, type, value, pitch, snake });
		});

		describe('And when I work with "id"', () => {
			it('should return the prize id', () => {
				expect(prize.id).to.equal(id);
			});

			it('should throw an error if trying to set the id', () => {
				expect(() => prize.id = 'new-id').to.throw();
			});
		});

		describe('And when I work with "type"', () => {
			it('should return the prize type', () => {
				expect(prize.type).to.equal(type);
			});

			it('should throw an error if trying to set the type', () => {
				expect(() => prize.type = PrizeType.APPLE).to.throw();
			});
		});

		describe('And when I work with "value"', () => {
			it('should return the prize value', () => {
				expect(prize.value).to.equal(value);
			});

			it('should throw an error if trying to set the value', () => {
				expect(() => prize.value = 20).to.throw();
			});
		});

		describe('And when I work with "position"', () => {
			it('should throw an error if trying to set the position directly', () => {
				expect(() => prize.position = new MockVector(1, 1)).to.throw();
			});
		});
	});

	describe('And I work with the Public methods', () => {
		beforeEach(() => {
			prize = new Prize({ id, type, value, pitch, snake });
		});

		describe('And I work with the collision method', () => {
			it('should throw an error if position argument is not a Vector', () => {
				expect(() => prize.collision('bad')).to.throw(`'position' argument must be an instance of Vector`);
			});

			it('should return false if no collision occurs', () => {
				const testPosition = prize.position.add(new MockVector(1, 1));
				expect(prize.collision(testPosition)).to.be.false;
			});

			it('should return true if collision occurs', () => {
				const testPosition = prize.position.clone();
				expect(prize.collision(testPosition)).to.be.true;
			});
		});
	});
});